### ISSUE TITLE
Write maybe some unit tests...

### ISSUE THREAD

**Issue by markushausammann** [cloud-solutions/zend-sentry#10]

**Comment by seyfer** [comment]
:+1:

**Comment by Mezzle** [comment]
:+1:

**Comment by pitbulk** [comment]
:+1:

**Comment by markushausammann** [comment]
Feel free to submit a pull request.

**Comment by markushausammann** [comment]
@nstapelbroek connected the repo to travis ci too, thanks for the contribution, feel free to provide more tests and refactoring suggestions. I'm currently working on a CSP solution which is tricky because Zend Framework overwrites identical headers which it should not according to HTTP specs.

**Comment by nstapelbroek** [comment]
Awesome, thank you for merging :muscle:

Do you have any specifics why the package conflicts with [zendframework/zendframework < 3.0.0](https://github.com/cloud-solutions/zend-sentry/blob/master/composer.json#L26)? I think a test around this requirement could be of good value :smile:

**Comment by markushausammann** [comment]
I don't remember exactly what it was, it had something to do with `ListenerAggregateInterface`. It must have been a BC break from 3 to 2 which doesn't allow to use the 3 series for ZF2. I've just stopped supporting the 2.* branch because I really don't care about ZF2 anymore.
