### ISSUE TITLE
JS not catch any error

### ISSUE THREAD

**Issue by apoca** [cloud-solutions/zend-sentry#40]
I can't catch any error in JS I think is because position of script:

<img width="1311" alt="captura de ecra 2015-12-24 as 02 20 11" src="https://cloud.githubusercontent.com/assets/5594091/11988300/6a0e6984-a9e5-11e5-8b39-487eb77a951a.png">

**Comment by markushausammann** [comment]
Two tips: 

- concat your assets
- use append and prepend to manipulate the loading sequence

**Comment by apoca** [comment]
Ok it's working now :)
