### ISSUE TITLE
Support zend-mvc 2.7.0 and above

### ISSUE THREAD

**Issue by aimfeld** [cloud-solutions/zend-sentry#41]
As of zf-2.5.3 (which currently installs zend-mvc 2.7.0), zend-sentry does not work anymore.

```
Fatal error: Call to undefined method Zend\Mvc\View\Http\ViewManager::getExceptionStrategy() in /app/vendor/cloud-solutions/zend-sentry/Module.php on line 182
```

Maybe a new major zend-sentry version 2.0.0 is needed to support zend-mvc >= 2.7.0.

**Comment by seyfer** [comment]
`Call to undefined method Zend\Mvc\View\Http\ViewManager::getExceptionStrategy()`

same error here!

**Comment by markushausammann** [comment]
I'll release a compatible version asap.

**Comment by markushausammann** [comment]
Fixed.
