### ISSUE TITLE
Not compatible with sentry/sentry 0.20.0

### ISSUE THREAD

**Issue by Mezzle** [cloud-solutions/zend-sentry#43]
Attempting to install via composer causes a failure.

**Comment by markushausammann** [comment]
Which version of the package did you try to install?

**Comment by Mezzle** [comment]
I'd done the following 

```
composer require sentry/sentry
composer require cloud-solutions/zend-sentry
```

**Comment by markushausammann** [comment]
You don't need to require `sentry/sentry`, it's a dependency of the latest `zend-sentry` version.

Just edit your `composer.json` to add the following entry to your required packages:

    {   
        "require": {
            "cloud-solutions/zend-sentry": "2.1.0",
            ....other packages
    }

**Comment by markushausammann** [comment]
Version `2.1.*` will install with `sentry/sentry`.

**Comment by markushausammann** [comment]
It's true that it won't install version `0.20.0` though. For that you'll have to wait until I update and publish a new version of `zend-sentry`. You should not install dependencies of dependencies manually, that leads to conflicts, as you can see. I used to get notifications when new sentry versions were available, it seems I don't get them anymore and need to look into that. You can expect a new `zend-sentry` version with the latest `sentry/sentry` version soonish.

**Comment by markushausammann** [comment]
https://github.com/cloud-solutions/zend-sentry/releases/tag/2.2.0
