### ISSUE TITLE
Zend3 issue

### ISSUE THREAD

**Issue by sharksoft** [cloud-solutions/zend-sentry#50]
Hi, on Zend adding zend-sentry I have this error
Zend\ServiceManager\Exception\ServiceNotFoundException
Unable to resolve service "viewhelpermanager" to a factory; are you certain you provided it during configuration?

I used version 3.0.0 of zend-entry

PS. Copying Module.php  from source it works

**Comment by sharksoft** [comment]
Hi, you can create a new release with last commits?
The sources in the github is work well, but the release is not updatet

**Comment by markushausammann** [comment]
Hi, I don't quite understand what you mean. I think 3.0.0 has all the changes. Which commit do you you think is missing in that release?

**Comment by markushausammann** [comment]
Oh, I see, sorry. Two commits are missing, how weird, I wasn't aware of that.

**Comment by sharksoft** [comment]
Module.php for zend3 is different

**Comment by markushausammann** [comment]
Can you please test the new `3.0.1` release.

**Comment by sharksoft** [comment]
It's works, thanks
