### ISSUE TITLE
How can I add 'extra' context when trigger an event ?

### ISSUE THREAD

**Issue by smknstd** [cloud-solutions/zend-sentry#51]
I tried something like:

```
            $this->getEventManager()->trigger('log', $this, array(
                'priority' => \Zend\Log\Logger::INFO,
                'message' => 'My message',
                'tags' => ['type' => 'test'],
                'extra' => ['my_extra_attribute' => 'toto@email.com']
            ));
```

but does not seem to work. I only got some result with:

```
            $ravenClient = $this->getServiceLocator()->get('raven');
            $ravenClient->extra_context(['my_extra_attribute' => 'toto@gmail.com']);
```

Any idea ? Thanx a lot

**Comment by markushausammann** [comment]
@aimfeld do you have News regarding this topic?

**Comment by aimfeld** [comment]
@smknstd 
We also use the raven client to add extra attributes, I don't think zend-sentry supports passing extra attributes to be logged.
The following works using ZF2 and ZF3:
```
$serviceManager = $mvcEvent->getApplication()->getServiceManager();
if ($serviceManager->has('raven')) {
    $ravenClient = $serviceManager->get('raven');
    $ravenClient->tags_context(
        [
            'locale'  => $this->translator()->getLocale(),
             ...
        ]
    );
}
```
It would be a great feature to pass an attribute array of strings as an optional `extra` parameter, as suggested. Implementation would be quite easy I think.

**Comment by aimfeld** [comment]
The above code sample is from a controller onDispatch() method, btw.

**Comment by markushausammann** [comment]
I fixed the documentation, are you interested in submitting a pull request for the solution you're proposing @smknstd ?

**Comment by smknstd** [comment]
https://github.com/cloud-solutions/zend-sentry/pull/52

Seems to work fine

![screeshot](http://imgur.com/a/jOM6C)

**Comment by markushausammann** [comment]
Thanks, I made two new releases.
