### ISSUE TITLE
Sentry-php 2.0

### ISSUE THREAD

**Issue by tradingstratagem** [cloud-solutions/zend-sentry#62]
Hello,

Do you plan to update to the new sentry 2.0?

https://github.com/getsentry/sentry-php/blob/master/UPGRADE-2.0.md

**Comment by markushausammann** [comment]
I'll have to look into it, seems like quite a big change.

**Comment by markushausammann** [comment]
Any pointers on what to look out for and what the challenges could be?

**Comment by tradingstratagem** [comment]
There is the migration guide https://github.com/getsentry/sentry-php/blob/master/UPGRADE-2.0.md

**Comment by markushausammann** [comment]
Yeah, I'll have to upgrade for sure. Seems like maybe I don't have to change the public interface of ZendSentry much, which would be a plus for ZendSentry users.

**Comment by markushausammann** [comment]
Are you interested in helping out with this?

**Comment by tradingstratagem** [comment]
Hello,

I can help you on this but at the end fo June at the moment I have no time to do the migration.

**Comment by markushausammann** [comment]
I'm starting to think that using the SDKs directly might be a better idea than maintaining this intermediary package.

**Comment by tradingstratagem** [comment]
Yes, could be a solution, this package simplify only a bit the integration maybe, but I think it's not too hard to integrate sentry without this package

**Comment by markushausammann** [comment]
Yeah, I think the maintenance effort is too much for the level of simplification this creates. At least with the new SDKs, integration is really very easy.
